name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Migrate DB
        run: npm run db:migrate
      - name: Start server
        run: |
          nohup npm start >/dev/null 2>&1 &
          for i in {1..30}; do
            if curl -sS http://127.0.0.1:3000/health | grep -q 'ok'; then
              echo 'Server is up'; break; fi; sleep 1; done
      - name: Run tests
        run: npm test


